=== Swagger-Training/swagger-training/labs/01_json_schema/solution/policy.map.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"description": "A policy",
	"properties": {
		"id": {
			"type": "string",
			"format": "uuid"
		},
		"title": {
			"type": "string",
			"description": "The title of the policy",
			"maxLength": 50
		},
		"policyType": {
			"type": "string",
			"description": "A valid policy type",
			"enum": [
				"privacy",
				"cookie",
				"terms"
			]
		},
		"audience": {
			"type": "string",
			"description": "The target audience",
			"enum": [
				"regional",
				"international"
			],
			"default": "international"
		},
		"defaultLanguage": {
			"$ref": "#/definitions/language"
		},
		"mandatory": {
			"type": "boolean",
			"default": false
		},
		"translations": {
            "patternProperties": {
                "^[a-z]{2}$": {
                      "$ref": "#/definitions/translation"
                }
            },
            "additionalProperties": false
		}
	},
	"required": [
		"id",
		"title",
		"policyType"
	],
	"example": {
		"id": "1b35ca9f-8413-4428-aa46-57ed68ea616a",
		"title": "Privacy Policy International",
		"policyType": "privacy",
		"audience": "International",
		"defaultLanguage": "en",
		"mandatory": true,
		"translations": [
			{
				"title": "سياسة الخصوصية الخاصة بريد بول",
				"releaseDate": "2017-04-21T11:50:37.358Z",
				"language": "ar",
				"version": 1
			},
			{
				"title": "Privacy Policy,",
				"releaseDate": "2017-10-27T07:33:29.725Z",
				"language": "en",
				"version": 2
			}
		]
	},
	"definitions": {
		"translation": {
			"type": "object",
			"description": "A translation for policy",
			"properties": {
				"title": {
					"type": "string",
					"description": "The localized title of the policyType"
				},
				"releaseDate": {
					"type": "string",
					"format": "date-time",
					"description": "The release date of the translation revision"
				},
				"language": {
					"$ref": "#/definitions/language"
				},
				"version": {
					"type": "integer",
					"description": "the major version of the policy translations"
				}
			},
			"required": [
				"title",
				"releaseDate",
				"version"
			]
		},
		"language": {
			"type": "string",
			"description": "A policy language",
			"minLength": 2,
			"maxLength": 2,
			"default": "en",
			"example": "de"
		}
	}
}

=== Swagger-Training/swagger-training/labs/01_json_schema/policy.json
{
  "id": "1b35ca9f-8413-4428-aa46-57ed68ea616a",
  "title": "Privacy Policy International",
  "audience": "international",
  "defaultLanguage": "en",
  "policyType": "privacy",
  "mandatory": true,
  "translations": [
    {
      "title": "سياسة الخصوصية الخاصة بريد بول",
      "releaseDate": "2017-04-21T11:50:37.358Z",
      "language": "ar",
      "version": 1
    },
    {
      "title": "Privacy Policy",
      "releaseDate": "2017-10-27T07:33:29.725Z",
      "language": "en",
      "version": 2
    },
    {
      "releaseDate": "2017-10-24T16:18:58.746Z",
      "title": "Politique de confidentialité",
      "language": "fr",
      "version": 2
    },
    {
      "title": "紅牛隱私權政策",
      "releaseDate": "2017-04-21T08:36:54.942Z",
      "language": "zh",
      "version": 1
    },
    {
      "title": "Política de Privacidad",
      "releaseDate": "2016-11-07T13:37:01.452Z",
      "language": "es",
      "version": 2
    },
    {
      "title": "Datenschutzrichtlinie",
      "releaseDate": "2017-08-04T13:32:10.223Z",
      "language": "de",
      "version": 2
    }
  ]
}

=== Swagger-Training/swagger-training/labs/01_json_schema/policy.map.json
{
    "id": "1b35ca9f-8413-4428-aa46-57ed68ea616a",
    "title": "Privacy Policy International",
    "audience": "international",
    "defaultLanguage": "en",
    "policyType": "privacy",
    "mandatory": true,
    "translations": {
        "ar": {
            "title": "سياسة الخصوصية الخاصة بريد بول",
            "releaseDate": "2017-04-21T11:50:37.358Z",
            "version": 1
        },
        "en": {
            "title": "Privacy Policy",
            "releaseDate": "2017-10-27T07:33:29.725Z",
            "version": 2
        },
        "fr": {
            "releaseDate": "2017-10-24T16:18:58.746Z",
            "title": "Politique de confidentialité",
            "version": 2
        },
        "zh": {
            "title": "紅牛隱私權政策",
            "releaseDate": "2017-04-21T08:36:54.942Z",
            "version": 1
        },
        "es": {
            "title": "Política de Privacidad",
            "releaseDate": "2016-11-07T13:37:01.452Z",
            "version": 2
        },
        "de": {
            "title": "Datenschutzrichtlinie",
            "releaseDate": "2017-08-04T13:32:10.223Z",
            "version": 2
        }
    }
}
